- id: clang-format
  name: clang-format
  description: Format files with ClangFormat.
  entry: clang-format
  language: system
  files: \.(c|cc|cxx|cpp|h|hpp|hxx)$
  args: ['-fallback-style=none', '-i']
- id: 'clang-format-6.0'
  name: 'clang-format-6.0'
  description: 'Format files with ClangFormat v6.'
  entry: 'clang-format-6.0'
  language: system
  files: \.(c|cc|cxx|cpp|h|hpp|hxx)$
  args: ['-fallback-style=none', '-i']
- id: 'clang-tidy-6.0'
  name: 'clang-tidy-6.0'
  description: 'Use the linter Clang-tidy v6.'
  entry: 'run_clang_tidy_on_diff'
  language: system
  files: \.(c|cc|cxx|cpp|h|hpp|hxx)$
  args: ['-b=_buildRelease', '-r=CanalTP', '-s=/app/navitia']
